module.exports = {
  data: [
    {
      id: 1,
      name: "Naveed Desai",
      gender: "male",
      age: 27,
      contact: { email: "naveed.desai@example.com", phone: "9008888569" },
      address: {
        street: "12 MG Road",
        city: "Bengaluru",
        state: "Karnataka",
        pincode: "560001",
      },
      skills: ["JavaScript", "Node.js", "React"],
      hobbies: ["Cricket", "Photography", "Reading"],
    },
    {
      id: 2,
      name: "Aisha Khan",
      gender: "female",
      age: 30,
      contact: { email: "aisha.khan@example.com", phone: "9822334455" },
      address: {
        street: "45 Marine Drive",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400020",
      },
      skills: ["Python", "Django", "Machine Learning"],
      hobbies: ["Traveling", "Cooking", "Music"],
    },
    {
      id: 3,
      name: "Ravi Sharma",
      gender: "male",
      age: 25,
      contact: { email: "ravi.sharma@example.com", phone: "9911223344" },
      address: {
        street: "7 Nehru Street",
        city: "Chennai",
        state: "Tamil Nadu",
        pincode: "600001",
      },
      skills: ["Java", "Spring Boot", "SQL"],
      hobbies: ["Cycling", "Gaming", "Movies"],
    },
    {
      id: 4,
      name: "Priya Mehta",
      gender: "female",
      age: 29,
      contact: { email: "priya.mehta@example.com", phone: "9845001122" },
      address: {
        street: "89 Park Avenue",
        city: "Pune",
        state: "Maharashtra",
        pincode: "411001",
      },
      skills: ["HTML", "CSS", "UI/UX Design"],
      hobbies: ["Painting", "Blogging", "Yoga"],
    },
    {
      id: 5,
      name: "Aman Verma",
      gender: "male",
      age: 32,
      contact: { email: "aman.verma@example.com", phone: "9876543210" },
      address: {
        street: "23 MG Road",
        city: "Delhi",
        state: "Delhi",
        pincode: "110001",
      },
      skills: ["C#", ".NET", "Azure"],
      hobbies: ["Football", "Photography", "Cooking"],
    },
    {
      id: 6,
      name: "Sneha Patil",
      gender: "female",
      age: 26,
      contact: { email: "sneha.patil@example.com", phone: "9812345678" },
      address: {
        street: "56 FC Road",
        city: "Pune",
        state: "Maharashtra",
        pincode: "411005",
      },
      skills: ["Flutter", "Firebase", "Dart"],
      hobbies: ["Traveling", "Music", "Reading"],
    },
    {
      id: 7,
      name: "Karan Gupta",
      gender: "male",
      age: 28,
      contact: { email: "karan.gupta@example.com", phone: "9871122334" },
      address: {
        street: "88 Golf Links",
        city: "Delhi",
        state: "Delhi",
        pincode: "110003",
      },
      skills: ["React Native", "Redux", "JavaScript"],
      hobbies: ["Running", "Swimming", "Chess"],
    },
    {
      id: 8,
      name: "Neha Reddy",
      gender: "female",
      age: 31,
      contact: { email: "neha.reddy@example.com", phone: "9900112233" },
      address: {
        street: "12 Jubilee Hills",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500033",
      },
      skills: ["AWS", "DevOps", "Linux"],
      hobbies: ["Cooking", "Trekking", "Movies"],
    },
    {
      id: 9,
      name: "Vikram Singh",
      gender: "male",
      age: 34,
      contact: { email: "vikram.singh@example.com", phone: "9877001122" },
      address: {
        street: "34 Civil Lines",
        city: "Jaipur",
        state: "Rajasthan",
        pincode: "302001",
      },
      skills: ["Golang", "Kubernetes", "Docker"],
      hobbies: ["Photography", "Travel", "Gardening"],
    },
    {
      id: 10,
      name: "Divya Nair",
      gender: "female",
      age: 24,
      contact: { email: "divya.nair@example.com", phone: "9811223344" },
      address: {
        street: "78 MG Road",
        city: "Kochi",
        state: "Kerala",
        pincode: "682016",
      },
      skills: ["PHP", "Laravel", "MySQL"],
      hobbies: ["Singing", "Dancing", "Reading"],
    },
  ],
};
